[project]
description = ""
name = "demo"
requires-python = "~=3.11.13"
version = "0.1.0"
# Runtime dependencies are not managed here yet.
dependencies = [
    "uvicorn==0.35",
    "fastapi==0.116.1",
    "numpy==1.26.4",
    "python-multipart==0.0.27",
]

[dependency-groups]
test = [
    "pytest ~= 9.0.2",
]
typecheck = [
    "mypy == 1.19.1",
]
